### ISSUE TITLE
Yang Belum

### ISSUE THREAD

**Issue by aja-x** [aliffiansyahm/jodohin#45]
- Search bar gede di header
- Notif: chat, notif biasa
- ~~Profile setting~~
- Chat
- Respon colek di notif colek
- Landing page & site/index~~
- Check all link (broken apa enggak)
- ~~Tambah followers~~
- Left bar
- Right bar kurang link ke buka chat sama ~~saling follow~~
- Update dan fix semua foto -> lulu
- ~~Landing & site/index~~ -> verent
- Update tabel pengguna tambahin kolom FOTOHEADER setelah kolom FOTO -> BUAT SEMUA!!

**Comment by aliffiansyah** [comment]
ok

**Comment by aja-x** [comment]
- Left bar
- Right bar kurang link ke buka chat sama saling follow

**Comment by aja-x** [comment]
- Update dan fix semua foto -> lulu

**Comment by aja-x** [comment]
- Landing & site/index -> `verent`

**Comment by aja-x** [comment]
- Update tabel `pengguna` tambahin kolom `FOTOHEADER` setelah kolom `FOTO`  -> BUAT SEMUA!!

**Comment by aja-x** [comment]
- Profile setting -> `lulu`

**Comment by aja-x** [comment]
- Right bar kurang link ke buka chat sama saling follow -> jarir
- Respon colek di notif colek -> jarir
- Search bar gede di header -> jarir

**Comment by aja-x** [comment]
- Check all link (broken apa enggak) -> verent
